//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nasi_ispani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public int ApplicantId { get; set; }
        public string ApplicantName { get; set; }
        public string ApllicantSurname { get; set; }
        public decimal IdNumber { get; set; }
        public decimal CellNumber { get; set; }
        public decimal YearsOfExperience { get; set; }
        public string EmailAddress { get; set; }
        public string CurrentEmployer { get; set; }
        public decimal Current_Salary { get; set; }
        public decimal ExpectedSalary { get; set; }
        public string Resume { get; set; }
    }
}
